export const WRITING_TOPICS: string[] = [
  "Describe your ideal weekend and explain why it appeals to you.",
  "What is the most important invention of the last 100 years? Why?",
  "Should students be required to learn a foreign language? Argue your position.",
  "Describe a person who has influenced your life and explain how.",
  "What would you do if you could travel anywhere in the world?",
  "Do you think social media has more positive or negative effects on society?",
  "Describe your favorite meal and explain how to prepare it.",
  "What is one skill you wish you had learned earlier in life?",
  "Should governments invest more in space exploration? Why or why not?",
  "Describe a challenge you overcame and what you learned from it.",
  "What makes a good leader? Give examples to support your answer.",
  "Do you prefer living in a city or the countryside? Explain your preference.",
  "What is the role of technology in education?",
  "Describe a book or movie that changed your perspective on something.",
  "Should public transportation be free for everyone? Discuss.",
  "What is the most important quality in a friend?",
  "How has your hometown changed over the years?",
  "What would you change about your country's education system?",
  "Describe a tradition in your culture and explain its significance.",
  "Do you think working from home is better than working in an office?",
  "What is the biggest environmental problem today and how can we solve it?",
  "Describe your dream job and explain why it interests you.",
  "Should children have access to smartphones? At what age?",
  "What is the value of learning history?",
  "Describe a memorable trip you have taken.",
  "How do you handle stress and what techniques work best for you?",
  "What role does art play in society?",
  "Should college education be free? Argue your position.",
  "Describe a time when you had to make a difficult decision.",
  "What is more important: talent or hard work?",
  "How has the internet changed the way people communicate?",
  "Describe your morning routine and explain why you follow it.",
  "What are the benefits and drawbacks of globalization?",
  "Should animals be kept in zoos? Why or why not?",
  "Describe a hobby you enjoy and explain why it is meaningful to you.",
  "What qualities make a good teacher?",
  "How do you think AI will change the job market?",
  "Describe a cultural difference you have experienced.",
  "What is the importance of reading in the digital age?",
  "Should voting be mandatory? Discuss the pros and cons.",
  "Describe a goal you are currently working toward.",
  "What is the relationship between money and happiness?",
  "How can individuals reduce their carbon footprint?",
  "Describe a festival or celebration you enjoy.",
  "What are the advantages of learning multiple languages?",
  "Should there be limits on free speech? When and why?",
  "Describe a technological device you cannot live without.",
  "What is the most pressing issue facing young people today?",
  "How do cultural differences affect communication?",
  "Describe what success means to you.",
  "Should homework be abolished in schools? Argue your case.",
  "What are the benefits of volunteering?",
  "Describe a place that makes you feel peaceful.",
  "How has music influenced your life?",
  "What is the future of transportation?",
  "Describe a time when you helped someone.",
  "Should fast food be taxed more heavily? Why or why not?",
  "What makes a city a good place to live?",
  "Describe an experience that taught you something unexpected.",
  "How do you stay motivated when facing difficulties?",
  "What is the importance of physical exercise?",
  "Describe a news story that interested you recently.",
  "Should all plastic bags be banned? Discuss.",
  "What is the best way to learn a new language?",
  "Describe your favorite season and explain why you prefer it.",
  "How do advertisements influence our buying decisions?",
  "What role should parents play in their children's education?",
  "Describe a time when you disagreed with someone and how you resolved it.",
  "Should there be a universal basic income? Discuss.",
  "What is the most important lesson life has taught you?",
  "How do you balance work and personal life?",
  "Describe a technology that you think will be important in 10 years.",
  "What are the advantages of traveling alone versus with a group?",
  "Should sports athletes be considered role models?",
  "Describe what your life would be like 10 years from now.",
  "How has climate change affected your region?",
  "What is the purpose of museums in modern society?",
  "Describe a meal you shared with someone special.",
  "Should standardized testing be eliminated? Why or why not?",
  "What does it mean to be a responsible citizen?",
  "Describe a time when you stepped outside your comfort zone.",
  "How do different generations view technology?",
  "What is the importance of sleep for health and productivity?",
  "Describe a project you worked on that you are proud of.",
  "Should companies be required to offer parental leave?",
  "What can individuals do to promote peace in their communities?",
  "Describe your learning style and how it helps you study.",
  "How does weather affect your mood and daily activities?",
  "What are the ethics of genetic engineering?",
  "Describe something you would like to learn and explain why.",
  "How has your perspective on life changed as you have grown older?",
  "What is the impact of tourism on local communities?",
  "Describe a time when you received constructive criticism.",
  "Should there be a four-day work week? Discuss.",
  "What is the value of teamwork in achieving goals?",
  "Describe a public figure you admire and explain why.",
  "How can we bridge the digital divide in education?",
  "What is the relationship between food and culture?",
  "Describe a time when patience paid off for you.",
  "How should society address the issue of homelessness?",
  "What is the most interesting thing you have learned recently?",
];

export function getRandomTopic(): string {
  return WRITING_TOPICS[Math.floor(Math.random() * WRITING_TOPICS.length)];
}
